
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  scott.com:
    external:
      name: net_byfn

services:

  explorerdb.scott.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.scott.com
    hostname: explorerdb.scott.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - scott.com

  explorer.scott.com:
    image: hyperledger/explorer:latest
    container_name: explorer.scott.com
    hostname: explorer.scott.com
    environment:
      - DATABASE_HOST=explorerdb.scott.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=info
      - LOG_LEVEL_DB=info
      - LOG_LEVEL_CONSOLE=debug
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - /home/administrator/cpp-avneesh/workspace_scott/explorer/config.json:/opt/explorer/app/platform/fabric/config.json
      - /home/administrator/cpp-avneesh/workspace_scott/explorer/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - /home/administrator/cpp-avneesh/workspace_scott/explorer/organization:/opt/explorer/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.scott.com:
        condition: service_healthy
    networks:
      - scott.com
